---
title: "Introduction to hmmertools"
author: "Diego Diez"
date: "`r BiocStyle::doc_date()`"
package: "`r BiocStyle::pkg_ver('hmmertools')`"
output:
    rmarkdown::html_document
abstract: >
  Introduction to the hmmertools package.
vignette: >
 %\VignetteIndexEntry{Introduction to hmmertools}
 %\VignetteEngine{knitr::rmarkdown}
 %\VignetteEncoding{UTF-8}
---


```{r setup, include=FALSE}
library(BiocStyle)
library(hmmertools)
```

# Introduction

hmmertools enables to run hmmer from R using a docker image.

```{r}
h <- hmmertools::hmmer$new()
h
```

You can access methods help using `help = TRUE` or passing `args = "-h"` to HMMER methods.
```{r}
#h$hmmsearch(help = TRUE)
```

You can specify the output file. By default `hmmsearch` outputs tbl format.

```{r}
#seq <- system.file("files", "uniprot.fasta", package = "hmmertools")
#hmm <- system.file("files", "Ras.hmm", package = "hmmertools")
seq <- "uniprot.fasta"
hmm <- "Ras.hmm"
h$hmmsearch(hmmfile = hmm, seqdb = seq, outfile = "out.txt")
read.table("out.txt")
```

